-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

-- null-ls setup stuff
-- vim.g.null_ls.setup({
--   sources = {
--     null_ls.builtins.formatting.prettierd,
--     null_ls.builtins.formatting.stylua,
--     null_ls.builtins.formatting.eslint_d,
--     null_ls.builtins.formatting.black,
--     null_ls.builtins.formatting.rustfmt,
--   },
-- })
